apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  {{- with .Values.addgreen-fileupload.deploymentAnnotations }}
  {{ toYaml . | indent 4 }}
  {{- end }}
  {{- if .Values.addgreen-fileupload.image.stream }}
    image.openshift.io/triggers: |
      [{
        "from": {
          "kind": "ImageStreamTag",
          "name": "{{ .Values.addgreen-fileupload.image.name }}:{{ .Values.addgreen-fileupload.image.tag }}"
        },
        "fieldPath": "spec.template.spec.containers[?(@.name==\"tpp-addgreen-fileupload\")].image"
      }]
  {{- end }}
  name: {{ include "modelbank-tpp.fullname" . }}-addgreen-fileupload
  labels:
    {{- include "modelbank-tpp.labels" . | nindent 4 }}
    app.kubernetes.io/component: tpp-addgreen-fileupload
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "addgreen-fileupload.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "addgreen-fileupload.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "addgreen-fileupload.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
