version: "3.3"

services:
  addgreen-fileupload:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./upload-dir:/usr/app/upload-dir
    ports:
      - "8080:8080"

volumes:
    upload-dir:
      driver: local
