name: Build Maven project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 12, 13 ]
    name: Java ${{ matrix.java }} compile
    steps:
      - uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - run: mvn -f github-actions-java-maven/pom.xml clean compile
  
  build:
    runs-on: ubuntu-latest
    needs: compile
    name: Build Maven project
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build and test project
      run: mvn -f github-actions-java-maven/pom.xml clean verify
    - name: Upload Maven build artifact
      uses: actions/upload-artifact@v1
      with:
        name: artifact
        path: github-actions-java-maven/target/github-actions-java-maven.jar
        
  deploy: 
    runs-on: ubuntu-latest  
    needs: build 
    name: Build Docker container and deploy to Kubernetes
    steps:
    - uses: actions/checkout@v1
    - name: Download Maven build artifact
      uses: actions/download-artifact@v1
      with:
        name: artifact
    - name: Build Docker container
      run: |
        mkdir -p github-actions-java-maven/target
        mv artifact/github-actions-java-maven.jar github-actions-java-maven/target
        docker build -t addgreen-fileupload:0.0.1 github-actions-java-maven
    - name: Docker login
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Tags
      run: docker tag addgreen-fileupload:0.0.1 ${{ secrets.DOCKERHUB_USERNAME }}/addgreen-fileupload:0.0.1
    - name: Push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/addgreen-fileupload:0.0.1
