name: Build Maven project

on:
  push:
    branches: [ main ]
    pull_request:
      branches: [ main ]


jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 12, 13 ]
    name: Java ${{ matrix.java }} compile
    steps:
      - uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - run: mvn -f github-actions-java-maven/pom.xml clean compile
  build:
    runs-on: ubuntu-latest
    needs: compile
    name: Build Maven project
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build and test project
        run: mvn -f github-actions-java-maven/pom.xml clean verify
      - name: Upload Maven build artifact
        uses: actions/upload-artifact@v1
        with:
          name: artifact
          path: github-actions-java-maven/target/github-actions-java-maven.jar
  deploy-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build
        run: make server
      - name: Tags
        run: docker tag addgreen-fileupload ${{ secrets.DOCKERHUB_USERNAME }}/addgreen-fileupload:0.0.1
      - name: Push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/addgreen-fileupload:0.0.1

  deploy-oc:
    runs-on: ubuntu-latest
      steps:

        - name: OpenShift Action publish images
          uses: redhat-developer/openshift-actions@v1.1
          with:
            version: '0.0.1'
            openshift_server_url: ${{secrets.OPENSHIFT_SERVER_URL}}
            parameters: '{"username": "${{ secrets.USERNAME }}", "password": "${{ secrets.PASSWORD }}", "acceptUntrustedCerts": "true"}'
            cmd: |
              oc project addgreen-fileupload
              oc import-image  --confirm addgreen-fileupload:0.0.1
