name: deploy Maven project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy-oc:
      runs-on: ubuntu-latest
      steps:
        - name: OpenShift Action publish images
          uses: redhat-developer/openshift-actions@v1.1
          with:
            openshift_server_url: ${{secrets.OPENSHIFT_SERVER_URL}}
            parameters: '{"username": "${{ secrets.USERNAME }}", "password": "${{ secrets.PASSWORD }}", "acceptUntrustedCerts": "true"}'
            cmd: |
              oc project addgreen-fileupload
              oc import-image  --confirm addgreen-fileupload:0.0.1
